@url = http://localhost:3456/api 
# @url = http://47.115.88.159:8080/api
@json = Content-Type: application/json
@user1 = Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwNDQ3NjI3MGI2ODdjMzI0MGNiMTg2NyIsImlhdCI6MTYxNTEyNTUyMX0.GT4BTSKc5O_jVDlje81U_HWiC9QPkhrvzQKI2wN_FdY
@user2 = Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwNDQ3ODU5OWZmYjUyNGIyNDA2ZWJmYSIsImlhdCI6MTYxNTEzMzQ2N30.54n2BM3CyVlHCWzMX06L5mPrhiolRJ3sP83OY2zgfAc
@commentId = 604501b8b7f8c93b5cae4f31

### 接口测试
GET {{url}}

### 注册
POST {{url}}/register
{{json}}

{
    "username": "user3",
    "password": "123456",
    "nickname": "我是璃月的厨师香菱"
}

### 登录
POST {{url}}/login
{{json}}

{
    "username": "222222",
    "password": "222222"
}

### 用户列表
GET {{url}}/users

### 视频列表
get {{url}}/video
### 添加视频
post {{url}}/video
{{json}}

{
    "id": "bv001",
    "name": "原神攻略，12-3",
    "introduction": "视频简介",
    "category": "游戏"
}

### 用户信息
get {{url}}/user
{{user1}}


### 更新用户信息1
put {{url}}/user
{{user2}}
{{json}}

{
    "gender": 0,
    "nickname": "我永远爱诺艾尔33333",
    "userImg": "userimg1",
    "userDesc": "个性签名"
}

### 收藏视频
post {{url}}/video/like
{{user2}}
{{json}}

{
    "videoId": "bv003"
}

### 查询收藏状态
get {{url}}/video/like
{{user2}}
{{json}}

{
    "videoId": "bv002"
}

### 上传
post {{url}}/upload/multer


### 发表评论
POST {{url}}/comment
{{json}}
{{user2}}

{
    "content": "哈哈哈哈",
    "date": "03-05",
    "parentId": "60450234b7f8c93b5cae4f3b",
    "videoId": "bv0002"
}

### 获取评论
GET {{url}}/comment/bv0002

{

}



















