@url = http://localhost:3456/api 
# @url = http://47.115.88.159:8080/api
@json = Content-Type: application/json


### 接口测试
GET {{url}}

### 注册
POST {{url}}/register
{{json}}

{
    "username": "user1",
    "password": "123456"
}

### 登录
POST {{url}}/login
{{json}}

{
    "username": "user1",
    "password": "123456"
}

### 用户列表
GET {{url}}/users

### 视频列表
get {{url}}/video
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwNDExOTQ5Y2Q0MTEwNDcyNDVkNzQzNiIsImlhdCI6MTYxNDg3OTIxNn0.So8QWVh3Nc6epmB_jBfqkQhFOZtLxSEoyx0HjRTNi_I

### 添加视频
post {{url}}/video
{{json}}

{
    "id": "bv001",
    "name": "原神攻略，12-3",
    "introduction": "视频简介",
    "category": "游戏"

}













